name: Label Parent Issue on Child Issue Close

on:
  issues:
    types: [closed]

jobs:
  label-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Extract Parent Issue and Check Labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }} # Automatically sets the repo context
        run: |
          # Extract parent issue ID from the child issue body using sed
          PARENT_ISSUE=$(echo "${{ github.event.issue.body }}" | sed -n 's|.*github\.com/.*/issues/\([0-9]\+\).*|\1|p')

          # Check if the parent issue ID was found
          if [ -n "$PARENT_ISSUE" ]; then
            # Check if the parent issue has the "test" label
            if gh issue view "$PARENT_ISSUE" --repo "$REPOSITORY" --json labels | jq '.labels | any(.name == "test")'; then
              # If the "test" label is present, add the "test:require:retest" label
              gh issue edit "$PARENT_ISSUE" --add-label "test:require:retest" --repo "$REPOSITORY"
              echo "Added 'test:require:retest' label to parent issue #$PARENT_ISSUE."
            else
              echo "Parent issue #$PARENT_ISSUE does not have the 'test' label. No action taken."
            fi
          else
            echo "No parent issue found in the child issue body."
          fi
