# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Master:Deploy:Azure - vue3-spa-feature-template-master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '16'
        
    - name: npm install and Build App
      run: |
        npm install
        npm run build

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'vue3-spa-feature-template-master'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_469d96696c5f492e9967c115723cbb73 }}
        package: ./dist/
